name: deploy-website on aws with github actions self runner 


on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Checkout Current Directory
      run: pwd
    

    - name: Check run docker container 
      run: docker container ls 


    - name: Stop docker container that is running
      run: sudo docker container stop csn-nginx || true

    - name: Delete running docker container
      run: sudo docker container rm csn-nginx || true

    - name: Docker build image to start docker container
      run: sudo docker build -t csn-nginx .

    - name: create Docker container
      run: sudo docker container run --name csn-nginx -p 8080:80 -d csn-nginx
    


